# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hardware_endpoint_pb2 as hardware__endpoint__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hardware_endpoint_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HardwareEndpointStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/robot_hw_endpoint.grpc.HardwareEndpoint/Ping',
                request_serializer=hardware__endpoint__pb2.PingRequest.SerializeToString,
                response_deserializer=hardware__endpoint__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetBMSStatus = channel.unary_unary(
                '/robot_hw_endpoint.grpc.HardwareEndpoint/GetBMSStatus',
                request_serializer=hardware__endpoint__pb2.StatusRequest.SerializeToString,
                response_deserializer=hardware__endpoint__pb2.BMSResponse.FromString,
                _registered_method=True)
        self.BMSControl = channel.unary_unary(
                '/robot_hw_endpoint.grpc.HardwareEndpoint/BMSControl',
                request_serializer=hardware__endpoint__pb2.BMSRequest.SerializeToString,
                response_deserializer=hardware__endpoint__pb2.BMSResponse.FromString,
                _registered_method=True)
        self.GetIMUStatus = channel.unary_unary(
                '/robot_hw_endpoint.grpc.HardwareEndpoint/GetIMUStatus',
                request_serializer=hardware__endpoint__pb2.StatusRequest.SerializeToString,
                response_deserializer=hardware__endpoint__pb2.IMUResponse.FromString,
                _registered_method=True)
        self.IMUControl = channel.unary_unary(
                '/robot_hw_endpoint.grpc.HardwareEndpoint/IMUControl',
                request_serializer=hardware__endpoint__pb2.IMURequest.SerializeToString,
                response_deserializer=hardware__endpoint__pb2.IMUResponse.FromString,
                _registered_method=True)
        self.GetMotorStatus = channel.unary_unary(
                '/robot_hw_endpoint.grpc.HardwareEndpoint/GetMotorStatus',
                request_serializer=hardware__endpoint__pb2.StatusRequest.SerializeToString,
                response_deserializer=hardware__endpoint__pb2.MotorResponse.FromString,
                _registered_method=True)
        self.MotorControl = channel.unary_unary(
                '/robot_hw_endpoint.grpc.HardwareEndpoint/MotorControl',
                request_serializer=hardware__endpoint__pb2.MotorRequest.SerializeToString,
                response_deserializer=hardware__endpoint__pb2.MotorResponse.FromString,
                _registered_method=True)
        self.Camera = channel.unary_unary(
                '/robot_hw_endpoint.grpc.HardwareEndpoint/Camera',
                request_serializer=hardware__endpoint__pb2.CameraRequest.SerializeToString,
                response_deserializer=hardware__endpoint__pb2.CameraResponse.FromString,
                _registered_method=True)


class HardwareEndpointServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBMSStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BMSControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIMUStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IMUControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMotorStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MotorControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Camera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HardwareEndpointServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=hardware__endpoint__pb2.PingRequest.FromString,
                    response_serializer=hardware__endpoint__pb2.PingResponse.SerializeToString,
            ),
            'GetBMSStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBMSStatus,
                    request_deserializer=hardware__endpoint__pb2.StatusRequest.FromString,
                    response_serializer=hardware__endpoint__pb2.BMSResponse.SerializeToString,
            ),
            'BMSControl': grpc.unary_unary_rpc_method_handler(
                    servicer.BMSControl,
                    request_deserializer=hardware__endpoint__pb2.BMSRequest.FromString,
                    response_serializer=hardware__endpoint__pb2.BMSResponse.SerializeToString,
            ),
            'GetIMUStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIMUStatus,
                    request_deserializer=hardware__endpoint__pb2.StatusRequest.FromString,
                    response_serializer=hardware__endpoint__pb2.IMUResponse.SerializeToString,
            ),
            'IMUControl': grpc.unary_unary_rpc_method_handler(
                    servicer.IMUControl,
                    request_deserializer=hardware__endpoint__pb2.IMURequest.FromString,
                    response_serializer=hardware__endpoint__pb2.IMUResponse.SerializeToString,
            ),
            'GetMotorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMotorStatus,
                    request_deserializer=hardware__endpoint__pb2.StatusRequest.FromString,
                    response_serializer=hardware__endpoint__pb2.MotorResponse.SerializeToString,
            ),
            'MotorControl': grpc.unary_unary_rpc_method_handler(
                    servicer.MotorControl,
                    request_deserializer=hardware__endpoint__pb2.MotorRequest.FromString,
                    response_serializer=hardware__endpoint__pb2.MotorResponse.SerializeToString,
            ),
            'Camera': grpc.unary_unary_rpc_method_handler(
                    servicer.Camera,
                    request_deserializer=hardware__endpoint__pb2.CameraRequest.FromString,
                    response_serializer=hardware__endpoint__pb2.CameraResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_hw_endpoint.grpc.HardwareEndpoint', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot_hw_endpoint.grpc.HardwareEndpoint', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HardwareEndpoint(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_hw_endpoint.grpc.HardwareEndpoint/Ping',
            hardware__endpoint__pb2.PingRequest.SerializeToString,
            hardware__endpoint__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBMSStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_hw_endpoint.grpc.HardwareEndpoint/GetBMSStatus',
            hardware__endpoint__pb2.StatusRequest.SerializeToString,
            hardware__endpoint__pb2.BMSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BMSControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_hw_endpoint.grpc.HardwareEndpoint/BMSControl',
            hardware__endpoint__pb2.BMSRequest.SerializeToString,
            hardware__endpoint__pb2.BMSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIMUStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_hw_endpoint.grpc.HardwareEndpoint/GetIMUStatus',
            hardware__endpoint__pb2.StatusRequest.SerializeToString,
            hardware__endpoint__pb2.IMUResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IMUControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_hw_endpoint.grpc.HardwareEndpoint/IMUControl',
            hardware__endpoint__pb2.IMURequest.SerializeToString,
            hardware__endpoint__pb2.IMUResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMotorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_hw_endpoint.grpc.HardwareEndpoint/GetMotorStatus',
            hardware__endpoint__pb2.StatusRequest.SerializeToString,
            hardware__endpoint__pb2.MotorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MotorControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_hw_endpoint.grpc.HardwareEndpoint/MotorControl',
            hardware__endpoint__pb2.MotorRequest.SerializeToString,
            hardware__endpoint__pb2.MotorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Camera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_hw_endpoint.grpc.HardwareEndpoint/Camera',
            hardware__endpoint__pb2.CameraRequest.SerializeToString,
            hardware__endpoint__pb2.CameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
