// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: io.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from io.proto</summary>
public static partial class IoReflection {

  #region Descriptor
  /// <summary>File descriptor for io.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static IoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cghpby5wcm90byIrCg1FbXB0eVJlc3BvbnNlEhoKBHR5cGUYASABKA4yDC5N",
          "ZXNzYWdlVHlwZSJpCgtQaW5nUmVxdWVzdBIaCgR0eXBlGAEgASgOMgwuTWVz",
          "c2FnZVR5cGUSDgoGZGF0YV8wGAIgASgFEg4KBmRhdGFfMRgDIAEoBRIOCgZk",
          "YXRhXzIYBCABKAUSDgoGZGF0YV8zGAUgASgFImoKDFBpbmdSZXNwb25zZRIa",
          "CgR0eXBlGAEgASgOMgwuTWVzc2FnZVR5cGUSDgoGZGF0YV8wGAIgASgFEg4K",
          "BmRhdGFfMRgDIAEoBRIOCgZkYXRhXzIYBCABKAUSDgoGZGF0YV8zGAUgASgF",
          "Il4KCkJNU1JlcXVlc3QSGgoEdHlwZRgBIAEoDjIMLk1lc3NhZ2VUeXBlEhkK",
          "EW1haW5fYnVzX2FfZW5hYmxlGAIgASgIEhkKEW1haW5fYnVzX2JfZW5hYmxl",
          "GAMgASgIIpkCCgtCTVNSZXNwb25zZRIaCgR0eXBlGAEgASgOMgwuTWVzc2Fn",
          "ZVR5cGUSFgoOY2VsbF92b2x0YWdlXzEYAiABKAUSFgoOY2VsbF92b2x0YWdl",
          "XzIYAyABKAUSFgoOY2VsbF92b2x0YWdlXzMYBCABKAUSGgoSbWFpbl9idXNf",
          "YV92b2x0YWdlGAUgASgFEhoKEm1haW5fYnVzX2FfY3VycmVudBgGIAEoBRIa",
          "ChJtYWluX2J1c19iX3ZvbHRhZ2UYByABKAUSGgoSbWFpbl9idXNfYl9jdXJy",
          "ZW50GAggASgFEhoKEm1haW5fYnVzX2FfZW5hYmxlZBgJIAEoCBIaChJtYWlu",
          "X2J1c19iX2VuYWJsZWQYCiABKAgiKAoKSU1VUmVxdWVzdBIaCgR0eXBlGAEg",
          "ASgOMgwuTWVzc2FnZVR5cGUigAEKC0lNVVJlc3BvbnNlEhoKBHR5cGUYASAB",
          "KA4yDC5NZXNzYWdlVHlwZRIMCgRyb2xsGAIgASgFEg0KBXBpdGNoGAMgASgF",
          "EgsKA3lhdxgEIAEoBRINCgVncHNfeBgFIAEoBRINCgVncHNfeRgGIAEoBRIN",
          "CgVncHNfaBgHIAEoBSJ9CgxNb3RvclJlcXVlc3QSGgoEdHlwZRgBIAEoDjIM",
          "Lk1lc3NhZ2VUeXBlEhkKEXJlcXVpcmVkX3ZlbG9jaXR5GAIgASgFEhgKEG1h",
          "eGltdW1fdmVsb2NpdHkYAyABKAUSHAoUbWF4aW11bV9hY2NlbGVyYXRpb24Y",
          "BCABKAUiXgoNTW90b3JSZXNwb25zZRIaCgR0eXBlGAEgASgOMgwuTWVzc2Fn",
          "ZVR5cGUSGAoQY3VycmVudF92ZWxvY2l0eRgCIAEoBRIXCg9jdXJyZW50X2Vu",
          "Y29kZXIYAyABKAUqzQEKC01lc3NhZ2VUeXBlEgwKCE1TR19OT05FEAASFAoQ",
          "TVNHX1BJTkdfUkVRVUVTVBABEhUKEU1TR19QSU5HX1JFU1BPTlNFEAISEwoP",
          "TVNHX0JNU19SRVFVRVNUEAMSFAoQTVNHX0JNU19SRVNQT05TRRAEEhMKD01T",
          "R19JTVVfUkVRVUVTVBAFEhQKEE1TR19JTVVfUkVTUE9OU0UQBhIVChFNU0df",
          "TU9UT1JfUkVRVUVTVBAHEhYKEk1TR19NT1RPUl9SRVNQT05TRRAIYgZwcm90",
          "bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::EmptyResponse), global::EmptyResponse.Parser, new[]{ "Type" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PingRequest), global::PingRequest.Parser, new[]{ "Type", "Data0", "Data1", "Data2", "Data3" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PingResponse), global::PingResponse.Parser, new[]{ "Type", "Data0", "Data1", "Data2", "Data3" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::BMSRequest), global::BMSRequest.Parser, new[]{ "Type", "MainBusAEnable", "MainBusBEnable" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::BMSResponse), global::BMSResponse.Parser, new[]{ "Type", "CellVoltage1", "CellVoltage2", "CellVoltage3", "MainBusAVoltage", "MainBusACurrent", "MainBusBVoltage", "MainBusBCurrent", "MainBusAEnabled", "MainBusBEnabled" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::IMURequest), global::IMURequest.Parser, new[]{ "Type" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::IMUResponse), global::IMUResponse.Parser, new[]{ "Type", "Roll", "Pitch", "Yaw", "GpsX", "GpsY", "GpsH" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::MotorRequest), global::MotorRequest.Parser, new[]{ "Type", "RequiredVelocity", "MaximumVelocity", "MaximumAcceleration" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::MotorResponse), global::MotorResponse.Parser, new[]{ "Type", "CurrentVelocity", "CurrentEncoder" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum MessageType {
  [pbr::OriginalName("MSG_NONE")] MsgNone = 0,
  [pbr::OriginalName("MSG_PING_REQUEST")] MsgPingRequest = 1,
  [pbr::OriginalName("MSG_PING_RESPONSE")] MsgPingResponse = 2,
  [pbr::OriginalName("MSG_BMS_REQUEST")] MsgBmsRequest = 3,
  [pbr::OriginalName("MSG_BMS_RESPONSE")] MsgBmsResponse = 4,
  [pbr::OriginalName("MSG_IMU_REQUEST")] MsgImuRequest = 5,
  [pbr::OriginalName("MSG_IMU_RESPONSE")] MsgImuResponse = 6,
  [pbr::OriginalName("MSG_MOTOR_REQUEST")] MsgMotorRequest = 7,
  [pbr::OriginalName("MSG_MOTOR_RESPONSE")] MsgMotorResponse = 8,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EmptyResponse : pb::IMessage<EmptyResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EmptyResponse> _parser = new pb::MessageParser<EmptyResponse>(() => new EmptyResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EmptyResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EmptyResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EmptyResponse(EmptyResponse other) : this() {
    type_ = other.type_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EmptyResponse Clone() {
    return new EmptyResponse(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::MessageType type_ = global::MessageType.MsgNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MessageType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EmptyResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EmptyResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::MessageType.MsgNone) hash ^= Type.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::MessageType.MsgNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EmptyResponse other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::MessageType.MsgNone) {
      Type = other.Type;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// ping test
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PingRequest : pb::IMessage<PingRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PingRequest> _parser = new pb::MessageParser<PingRequest>(() => new PingRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PingRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IoReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PingRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PingRequest(PingRequest other) : this() {
    type_ = other.type_;
    data0_ = other.data0_;
    data1_ = other.data1_;
    data2_ = other.data2_;
    data3_ = other.data3_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PingRequest Clone() {
    return new PingRequest(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::MessageType type_ = global::MessageType.MsgNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MessageType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "data_0" field.</summary>
  public const int Data0FieldNumber = 2;
  private int data0_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Data0 {
    get { return data0_; }
    set {
      data0_ = value;
    }
  }

  /// <summary>Field number for the "data_1" field.</summary>
  public const int Data1FieldNumber = 3;
  private int data1_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Data1 {
    get { return data1_; }
    set {
      data1_ = value;
    }
  }

  /// <summary>Field number for the "data_2" field.</summary>
  public const int Data2FieldNumber = 4;
  private int data2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Data2 {
    get { return data2_; }
    set {
      data2_ = value;
    }
  }

  /// <summary>Field number for the "data_3" field.</summary>
  public const int Data3FieldNumber = 5;
  private int data3_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Data3 {
    get { return data3_; }
    set {
      data3_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PingRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PingRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (Data0 != other.Data0) return false;
    if (Data1 != other.Data1) return false;
    if (Data2 != other.Data2) return false;
    if (Data3 != other.Data3) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::MessageType.MsgNone) hash ^= Type.GetHashCode();
    if (Data0 != 0) hash ^= Data0.GetHashCode();
    if (Data1 != 0) hash ^= Data1.GetHashCode();
    if (Data2 != 0) hash ^= Data2.GetHashCode();
    if (Data3 != 0) hash ^= Data3.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Data0 != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Data0);
    }
    if (Data1 != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Data1);
    }
    if (Data2 != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Data2);
    }
    if (Data3 != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Data3);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Data0 != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Data0);
    }
    if (Data1 != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Data1);
    }
    if (Data2 != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Data2);
    }
    if (Data3 != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Data3);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::MessageType.MsgNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (Data0 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Data0);
    }
    if (Data1 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Data1);
    }
    if (Data2 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Data2);
    }
    if (Data3 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Data3);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PingRequest other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::MessageType.MsgNone) {
      Type = other.Type;
    }
    if (other.Data0 != 0) {
      Data0 = other.Data0;
    }
    if (other.Data1 != 0) {
      Data1 = other.Data1;
    }
    if (other.Data2 != 0) {
      Data2 = other.Data2;
    }
    if (other.Data3 != 0) {
      Data3 = other.Data3;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          Data0 = input.ReadInt32();
          break;
        }
        case 24: {
          Data1 = input.ReadInt32();
          break;
        }
        case 32: {
          Data2 = input.ReadInt32();
          break;
        }
        case 40: {
          Data3 = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          Data0 = input.ReadInt32();
          break;
        }
        case 24: {
          Data1 = input.ReadInt32();
          break;
        }
        case 32: {
          Data2 = input.ReadInt32();
          break;
        }
        case 40: {
          Data3 = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PingResponse : pb::IMessage<PingResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PingResponse> _parser = new pb::MessageParser<PingResponse>(() => new PingResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PingResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IoReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PingResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PingResponse(PingResponse other) : this() {
    type_ = other.type_;
    data0_ = other.data0_;
    data1_ = other.data1_;
    data2_ = other.data2_;
    data3_ = other.data3_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PingResponse Clone() {
    return new PingResponse(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::MessageType type_ = global::MessageType.MsgNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MessageType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "data_0" field.</summary>
  public const int Data0FieldNumber = 2;
  private int data0_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Data0 {
    get { return data0_; }
    set {
      data0_ = value;
    }
  }

  /// <summary>Field number for the "data_1" field.</summary>
  public const int Data1FieldNumber = 3;
  private int data1_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Data1 {
    get { return data1_; }
    set {
      data1_ = value;
    }
  }

  /// <summary>Field number for the "data_2" field.</summary>
  public const int Data2FieldNumber = 4;
  private int data2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Data2 {
    get { return data2_; }
    set {
      data2_ = value;
    }
  }

  /// <summary>Field number for the "data_3" field.</summary>
  public const int Data3FieldNumber = 5;
  private int data3_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Data3 {
    get { return data3_; }
    set {
      data3_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PingResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PingResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (Data0 != other.Data0) return false;
    if (Data1 != other.Data1) return false;
    if (Data2 != other.Data2) return false;
    if (Data3 != other.Data3) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::MessageType.MsgNone) hash ^= Type.GetHashCode();
    if (Data0 != 0) hash ^= Data0.GetHashCode();
    if (Data1 != 0) hash ^= Data1.GetHashCode();
    if (Data2 != 0) hash ^= Data2.GetHashCode();
    if (Data3 != 0) hash ^= Data3.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Data0 != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Data0);
    }
    if (Data1 != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Data1);
    }
    if (Data2 != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Data2);
    }
    if (Data3 != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Data3);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Data0 != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Data0);
    }
    if (Data1 != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Data1);
    }
    if (Data2 != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Data2);
    }
    if (Data3 != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Data3);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::MessageType.MsgNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (Data0 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Data0);
    }
    if (Data1 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Data1);
    }
    if (Data2 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Data2);
    }
    if (Data3 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Data3);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PingResponse other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::MessageType.MsgNone) {
      Type = other.Type;
    }
    if (other.Data0 != 0) {
      Data0 = other.Data0;
    }
    if (other.Data1 != 0) {
      Data1 = other.Data1;
    }
    if (other.Data2 != 0) {
      Data2 = other.Data2;
    }
    if (other.Data3 != 0) {
      Data3 = other.Data3;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          Data0 = input.ReadInt32();
          break;
        }
        case 24: {
          Data1 = input.ReadInt32();
          break;
        }
        case 32: {
          Data2 = input.ReadInt32();
          break;
        }
        case 40: {
          Data3 = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          Data0 = input.ReadInt32();
          break;
        }
        case 24: {
          Data1 = input.ReadInt32();
          break;
        }
        case 32: {
          Data2 = input.ReadInt32();
          break;
        }
        case 40: {
          Data3 = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// baterry power management
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class BMSRequest : pb::IMessage<BMSRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BMSRequest> _parser = new pb::MessageParser<BMSRequest>(() => new BMSRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BMSRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IoReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BMSRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BMSRequest(BMSRequest other) : this() {
    type_ = other.type_;
    mainBusAEnable_ = other.mainBusAEnable_;
    mainBusBEnable_ = other.mainBusBEnable_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BMSRequest Clone() {
    return new BMSRequest(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::MessageType type_ = global::MessageType.MsgNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MessageType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "main_bus_a_enable" field.</summary>
  public const int MainBusAEnableFieldNumber = 2;
  private bool mainBusAEnable_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool MainBusAEnable {
    get { return mainBusAEnable_; }
    set {
      mainBusAEnable_ = value;
    }
  }

  /// <summary>Field number for the "main_bus_b_enable" field.</summary>
  public const int MainBusBEnableFieldNumber = 3;
  private bool mainBusBEnable_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool MainBusBEnable {
    get { return mainBusBEnable_; }
    set {
      mainBusBEnable_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BMSRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BMSRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (MainBusAEnable != other.MainBusAEnable) return false;
    if (MainBusBEnable != other.MainBusBEnable) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::MessageType.MsgNone) hash ^= Type.GetHashCode();
    if (MainBusAEnable != false) hash ^= MainBusAEnable.GetHashCode();
    if (MainBusBEnable != false) hash ^= MainBusBEnable.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (MainBusAEnable != false) {
      output.WriteRawTag(16);
      output.WriteBool(MainBusAEnable);
    }
    if (MainBusBEnable != false) {
      output.WriteRawTag(24);
      output.WriteBool(MainBusBEnable);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (MainBusAEnable != false) {
      output.WriteRawTag(16);
      output.WriteBool(MainBusAEnable);
    }
    if (MainBusBEnable != false) {
      output.WriteRawTag(24);
      output.WriteBool(MainBusBEnable);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::MessageType.MsgNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (MainBusAEnable != false) {
      size += 1 + 1;
    }
    if (MainBusBEnable != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BMSRequest other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::MessageType.MsgNone) {
      Type = other.Type;
    }
    if (other.MainBusAEnable != false) {
      MainBusAEnable = other.MainBusAEnable;
    }
    if (other.MainBusBEnable != false) {
      MainBusBEnable = other.MainBusBEnable;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          MainBusAEnable = input.ReadBool();
          break;
        }
        case 24: {
          MainBusBEnable = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          MainBusAEnable = input.ReadBool();
          break;
        }
        case 24: {
          MainBusBEnable = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class BMSResponse : pb::IMessage<BMSResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BMSResponse> _parser = new pb::MessageParser<BMSResponse>(() => new BMSResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BMSResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IoReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BMSResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BMSResponse(BMSResponse other) : this() {
    type_ = other.type_;
    cellVoltage1_ = other.cellVoltage1_;
    cellVoltage2_ = other.cellVoltage2_;
    cellVoltage3_ = other.cellVoltage3_;
    mainBusAVoltage_ = other.mainBusAVoltage_;
    mainBusACurrent_ = other.mainBusACurrent_;
    mainBusBVoltage_ = other.mainBusBVoltage_;
    mainBusBCurrent_ = other.mainBusBCurrent_;
    mainBusAEnabled_ = other.mainBusAEnabled_;
    mainBusBEnabled_ = other.mainBusBEnabled_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BMSResponse Clone() {
    return new BMSResponse(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::MessageType type_ = global::MessageType.MsgNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MessageType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "cell_voltage_1" field.</summary>
  public const int CellVoltage1FieldNumber = 2;
  private int cellVoltage1_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CellVoltage1 {
    get { return cellVoltage1_; }
    set {
      cellVoltage1_ = value;
    }
  }

  /// <summary>Field number for the "cell_voltage_2" field.</summary>
  public const int CellVoltage2FieldNumber = 3;
  private int cellVoltage2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CellVoltage2 {
    get { return cellVoltage2_; }
    set {
      cellVoltage2_ = value;
    }
  }

  /// <summary>Field number for the "cell_voltage_3" field.</summary>
  public const int CellVoltage3FieldNumber = 4;
  private int cellVoltage3_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CellVoltage3 {
    get { return cellVoltage3_; }
    set {
      cellVoltage3_ = value;
    }
  }

  /// <summary>Field number for the "main_bus_a_voltage" field.</summary>
  public const int MainBusAVoltageFieldNumber = 5;
  private int mainBusAVoltage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MainBusAVoltage {
    get { return mainBusAVoltage_; }
    set {
      mainBusAVoltage_ = value;
    }
  }

  /// <summary>Field number for the "main_bus_a_current" field.</summary>
  public const int MainBusACurrentFieldNumber = 6;
  private int mainBusACurrent_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MainBusACurrent {
    get { return mainBusACurrent_; }
    set {
      mainBusACurrent_ = value;
    }
  }

  /// <summary>Field number for the "main_bus_b_voltage" field.</summary>
  public const int MainBusBVoltageFieldNumber = 7;
  private int mainBusBVoltage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MainBusBVoltage {
    get { return mainBusBVoltage_; }
    set {
      mainBusBVoltage_ = value;
    }
  }

  /// <summary>Field number for the "main_bus_b_current" field.</summary>
  public const int MainBusBCurrentFieldNumber = 8;
  private int mainBusBCurrent_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MainBusBCurrent {
    get { return mainBusBCurrent_; }
    set {
      mainBusBCurrent_ = value;
    }
  }

  /// <summary>Field number for the "main_bus_a_enabled" field.</summary>
  public const int MainBusAEnabledFieldNumber = 9;
  private bool mainBusAEnabled_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool MainBusAEnabled {
    get { return mainBusAEnabled_; }
    set {
      mainBusAEnabled_ = value;
    }
  }

  /// <summary>Field number for the "main_bus_b_enabled" field.</summary>
  public const int MainBusBEnabledFieldNumber = 10;
  private bool mainBusBEnabled_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool MainBusBEnabled {
    get { return mainBusBEnabled_; }
    set {
      mainBusBEnabled_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BMSResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BMSResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (CellVoltage1 != other.CellVoltage1) return false;
    if (CellVoltage2 != other.CellVoltage2) return false;
    if (CellVoltage3 != other.CellVoltage3) return false;
    if (MainBusAVoltage != other.MainBusAVoltage) return false;
    if (MainBusACurrent != other.MainBusACurrent) return false;
    if (MainBusBVoltage != other.MainBusBVoltage) return false;
    if (MainBusBCurrent != other.MainBusBCurrent) return false;
    if (MainBusAEnabled != other.MainBusAEnabled) return false;
    if (MainBusBEnabled != other.MainBusBEnabled) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::MessageType.MsgNone) hash ^= Type.GetHashCode();
    if (CellVoltage1 != 0) hash ^= CellVoltage1.GetHashCode();
    if (CellVoltage2 != 0) hash ^= CellVoltage2.GetHashCode();
    if (CellVoltage3 != 0) hash ^= CellVoltage3.GetHashCode();
    if (MainBusAVoltage != 0) hash ^= MainBusAVoltage.GetHashCode();
    if (MainBusACurrent != 0) hash ^= MainBusACurrent.GetHashCode();
    if (MainBusBVoltage != 0) hash ^= MainBusBVoltage.GetHashCode();
    if (MainBusBCurrent != 0) hash ^= MainBusBCurrent.GetHashCode();
    if (MainBusAEnabled != false) hash ^= MainBusAEnabled.GetHashCode();
    if (MainBusBEnabled != false) hash ^= MainBusBEnabled.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (CellVoltage1 != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(CellVoltage1);
    }
    if (CellVoltage2 != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(CellVoltage2);
    }
    if (CellVoltage3 != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(CellVoltage3);
    }
    if (MainBusAVoltage != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(MainBusAVoltage);
    }
    if (MainBusACurrent != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(MainBusACurrent);
    }
    if (MainBusBVoltage != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(MainBusBVoltage);
    }
    if (MainBusBCurrent != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(MainBusBCurrent);
    }
    if (MainBusAEnabled != false) {
      output.WriteRawTag(72);
      output.WriteBool(MainBusAEnabled);
    }
    if (MainBusBEnabled != false) {
      output.WriteRawTag(80);
      output.WriteBool(MainBusBEnabled);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (CellVoltage1 != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(CellVoltage1);
    }
    if (CellVoltage2 != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(CellVoltage2);
    }
    if (CellVoltage3 != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(CellVoltage3);
    }
    if (MainBusAVoltage != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(MainBusAVoltage);
    }
    if (MainBusACurrent != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(MainBusACurrent);
    }
    if (MainBusBVoltage != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(MainBusBVoltage);
    }
    if (MainBusBCurrent != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(MainBusBCurrent);
    }
    if (MainBusAEnabled != false) {
      output.WriteRawTag(72);
      output.WriteBool(MainBusAEnabled);
    }
    if (MainBusBEnabled != false) {
      output.WriteRawTag(80);
      output.WriteBool(MainBusBEnabled);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::MessageType.MsgNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (CellVoltage1 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CellVoltage1);
    }
    if (CellVoltage2 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CellVoltage2);
    }
    if (CellVoltage3 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CellVoltage3);
    }
    if (MainBusAVoltage != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MainBusAVoltage);
    }
    if (MainBusACurrent != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MainBusACurrent);
    }
    if (MainBusBVoltage != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MainBusBVoltage);
    }
    if (MainBusBCurrent != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MainBusBCurrent);
    }
    if (MainBusAEnabled != false) {
      size += 1 + 1;
    }
    if (MainBusBEnabled != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BMSResponse other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::MessageType.MsgNone) {
      Type = other.Type;
    }
    if (other.CellVoltage1 != 0) {
      CellVoltage1 = other.CellVoltage1;
    }
    if (other.CellVoltage2 != 0) {
      CellVoltage2 = other.CellVoltage2;
    }
    if (other.CellVoltage3 != 0) {
      CellVoltage3 = other.CellVoltage3;
    }
    if (other.MainBusAVoltage != 0) {
      MainBusAVoltage = other.MainBusAVoltage;
    }
    if (other.MainBusACurrent != 0) {
      MainBusACurrent = other.MainBusACurrent;
    }
    if (other.MainBusBVoltage != 0) {
      MainBusBVoltage = other.MainBusBVoltage;
    }
    if (other.MainBusBCurrent != 0) {
      MainBusBCurrent = other.MainBusBCurrent;
    }
    if (other.MainBusAEnabled != false) {
      MainBusAEnabled = other.MainBusAEnabled;
    }
    if (other.MainBusBEnabled != false) {
      MainBusBEnabled = other.MainBusBEnabled;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          CellVoltage1 = input.ReadInt32();
          break;
        }
        case 24: {
          CellVoltage2 = input.ReadInt32();
          break;
        }
        case 32: {
          CellVoltage3 = input.ReadInt32();
          break;
        }
        case 40: {
          MainBusAVoltage = input.ReadInt32();
          break;
        }
        case 48: {
          MainBusACurrent = input.ReadInt32();
          break;
        }
        case 56: {
          MainBusBVoltage = input.ReadInt32();
          break;
        }
        case 64: {
          MainBusBCurrent = input.ReadInt32();
          break;
        }
        case 72: {
          MainBusAEnabled = input.ReadBool();
          break;
        }
        case 80: {
          MainBusBEnabled = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          CellVoltage1 = input.ReadInt32();
          break;
        }
        case 24: {
          CellVoltage2 = input.ReadInt32();
          break;
        }
        case 32: {
          CellVoltage3 = input.ReadInt32();
          break;
        }
        case 40: {
          MainBusAVoltage = input.ReadInt32();
          break;
        }
        case 48: {
          MainBusACurrent = input.ReadInt32();
          break;
        }
        case 56: {
          MainBusBVoltage = input.ReadInt32();
          break;
        }
        case 64: {
          MainBusBCurrent = input.ReadInt32();
          break;
        }
        case 72: {
          MainBusAEnabled = input.ReadBool();
          break;
        }
        case 80: {
          MainBusBEnabled = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// IMU + GPS unit
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class IMURequest : pb::IMessage<IMURequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<IMURequest> _parser = new pb::MessageParser<IMURequest>(() => new IMURequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<IMURequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IoReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public IMURequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public IMURequest(IMURequest other) : this() {
    type_ = other.type_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public IMURequest Clone() {
    return new IMURequest(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::MessageType type_ = global::MessageType.MsgNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MessageType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as IMURequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(IMURequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::MessageType.MsgNone) hash ^= Type.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::MessageType.MsgNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(IMURequest other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::MessageType.MsgNone) {
      Type = other.Type;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class IMUResponse : pb::IMessage<IMUResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<IMUResponse> _parser = new pb::MessageParser<IMUResponse>(() => new IMUResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<IMUResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IoReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public IMUResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public IMUResponse(IMUResponse other) : this() {
    type_ = other.type_;
    roll_ = other.roll_;
    pitch_ = other.pitch_;
    yaw_ = other.yaw_;
    gpsX_ = other.gpsX_;
    gpsY_ = other.gpsY_;
    gpsH_ = other.gpsH_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public IMUResponse Clone() {
    return new IMUResponse(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::MessageType type_ = global::MessageType.MsgNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MessageType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "roll" field.</summary>
  public const int RollFieldNumber = 2;
  private int roll_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Roll {
    get { return roll_; }
    set {
      roll_ = value;
    }
  }

  /// <summary>Field number for the "pitch" field.</summary>
  public const int PitchFieldNumber = 3;
  private int pitch_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Pitch {
    get { return pitch_; }
    set {
      pitch_ = value;
    }
  }

  /// <summary>Field number for the "yaw" field.</summary>
  public const int YawFieldNumber = 4;
  private int yaw_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Yaw {
    get { return yaw_; }
    set {
      yaw_ = value;
    }
  }

  /// <summary>Field number for the "gps_x" field.</summary>
  public const int GpsXFieldNumber = 5;
  private int gpsX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GpsX {
    get { return gpsX_; }
    set {
      gpsX_ = value;
    }
  }

  /// <summary>Field number for the "gps_y" field.</summary>
  public const int GpsYFieldNumber = 6;
  private int gpsY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GpsY {
    get { return gpsY_; }
    set {
      gpsY_ = value;
    }
  }

  /// <summary>Field number for the "gps_h" field.</summary>
  public const int GpsHFieldNumber = 7;
  private int gpsH_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GpsH {
    get { return gpsH_; }
    set {
      gpsH_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as IMUResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(IMUResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (Roll != other.Roll) return false;
    if (Pitch != other.Pitch) return false;
    if (Yaw != other.Yaw) return false;
    if (GpsX != other.GpsX) return false;
    if (GpsY != other.GpsY) return false;
    if (GpsH != other.GpsH) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::MessageType.MsgNone) hash ^= Type.GetHashCode();
    if (Roll != 0) hash ^= Roll.GetHashCode();
    if (Pitch != 0) hash ^= Pitch.GetHashCode();
    if (Yaw != 0) hash ^= Yaw.GetHashCode();
    if (GpsX != 0) hash ^= GpsX.GetHashCode();
    if (GpsY != 0) hash ^= GpsY.GetHashCode();
    if (GpsH != 0) hash ^= GpsH.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Roll != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Roll);
    }
    if (Pitch != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Pitch);
    }
    if (Yaw != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Yaw);
    }
    if (GpsX != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(GpsX);
    }
    if (GpsY != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(GpsY);
    }
    if (GpsH != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(GpsH);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Roll != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Roll);
    }
    if (Pitch != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Pitch);
    }
    if (Yaw != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Yaw);
    }
    if (GpsX != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(GpsX);
    }
    if (GpsY != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(GpsY);
    }
    if (GpsH != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(GpsH);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::MessageType.MsgNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (Roll != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Roll);
    }
    if (Pitch != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pitch);
    }
    if (Yaw != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Yaw);
    }
    if (GpsX != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GpsX);
    }
    if (GpsY != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GpsY);
    }
    if (GpsH != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GpsH);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(IMUResponse other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::MessageType.MsgNone) {
      Type = other.Type;
    }
    if (other.Roll != 0) {
      Roll = other.Roll;
    }
    if (other.Pitch != 0) {
      Pitch = other.Pitch;
    }
    if (other.Yaw != 0) {
      Yaw = other.Yaw;
    }
    if (other.GpsX != 0) {
      GpsX = other.GpsX;
    }
    if (other.GpsY != 0) {
      GpsY = other.GpsY;
    }
    if (other.GpsH != 0) {
      GpsH = other.GpsH;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          Roll = input.ReadInt32();
          break;
        }
        case 24: {
          Pitch = input.ReadInt32();
          break;
        }
        case 32: {
          Yaw = input.ReadInt32();
          break;
        }
        case 40: {
          GpsX = input.ReadInt32();
          break;
        }
        case 48: {
          GpsY = input.ReadInt32();
          break;
        }
        case 56: {
          GpsH = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          Roll = input.ReadInt32();
          break;
        }
        case 24: {
          Pitch = input.ReadInt32();
          break;
        }
        case 32: {
          Yaw = input.ReadInt32();
          break;
        }
        case 40: {
          GpsX = input.ReadInt32();
          break;
        }
        case 48: {
          GpsY = input.ReadInt32();
          break;
        }
        case 56: {
          GpsH = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// motor controll unit
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class MotorRequest : pb::IMessage<MotorRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MotorRequest> _parser = new pb::MessageParser<MotorRequest>(() => new MotorRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MotorRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IoReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MotorRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MotorRequest(MotorRequest other) : this() {
    type_ = other.type_;
    requiredVelocity_ = other.requiredVelocity_;
    maximumVelocity_ = other.maximumVelocity_;
    maximumAcceleration_ = other.maximumAcceleration_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MotorRequest Clone() {
    return new MotorRequest(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::MessageType type_ = global::MessageType.MsgNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MessageType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "required_velocity" field.</summary>
  public const int RequiredVelocityFieldNumber = 2;
  private int requiredVelocity_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RequiredVelocity {
    get { return requiredVelocity_; }
    set {
      requiredVelocity_ = value;
    }
  }

  /// <summary>Field number for the "maximum_velocity" field.</summary>
  public const int MaximumVelocityFieldNumber = 3;
  private int maximumVelocity_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MaximumVelocity {
    get { return maximumVelocity_; }
    set {
      maximumVelocity_ = value;
    }
  }

  /// <summary>Field number for the "maximum_acceleration" field.</summary>
  public const int MaximumAccelerationFieldNumber = 4;
  private int maximumAcceleration_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MaximumAcceleration {
    get { return maximumAcceleration_; }
    set {
      maximumAcceleration_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MotorRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MotorRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (RequiredVelocity != other.RequiredVelocity) return false;
    if (MaximumVelocity != other.MaximumVelocity) return false;
    if (MaximumAcceleration != other.MaximumAcceleration) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::MessageType.MsgNone) hash ^= Type.GetHashCode();
    if (RequiredVelocity != 0) hash ^= RequiredVelocity.GetHashCode();
    if (MaximumVelocity != 0) hash ^= MaximumVelocity.GetHashCode();
    if (MaximumAcceleration != 0) hash ^= MaximumAcceleration.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (RequiredVelocity != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(RequiredVelocity);
    }
    if (MaximumVelocity != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(MaximumVelocity);
    }
    if (MaximumAcceleration != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(MaximumAcceleration);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (RequiredVelocity != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(RequiredVelocity);
    }
    if (MaximumVelocity != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(MaximumVelocity);
    }
    if (MaximumAcceleration != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(MaximumAcceleration);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::MessageType.MsgNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (RequiredVelocity != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RequiredVelocity);
    }
    if (MaximumVelocity != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaximumVelocity);
    }
    if (MaximumAcceleration != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaximumAcceleration);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MotorRequest other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::MessageType.MsgNone) {
      Type = other.Type;
    }
    if (other.RequiredVelocity != 0) {
      RequiredVelocity = other.RequiredVelocity;
    }
    if (other.MaximumVelocity != 0) {
      MaximumVelocity = other.MaximumVelocity;
    }
    if (other.MaximumAcceleration != 0) {
      MaximumAcceleration = other.MaximumAcceleration;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          RequiredVelocity = input.ReadInt32();
          break;
        }
        case 24: {
          MaximumVelocity = input.ReadInt32();
          break;
        }
        case 32: {
          MaximumAcceleration = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          RequiredVelocity = input.ReadInt32();
          break;
        }
        case 24: {
          MaximumVelocity = input.ReadInt32();
          break;
        }
        case 32: {
          MaximumAcceleration = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class MotorResponse : pb::IMessage<MotorResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MotorResponse> _parser = new pb::MessageParser<MotorResponse>(() => new MotorResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MotorResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IoReflection.Descriptor.MessageTypes[8]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MotorResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MotorResponse(MotorResponse other) : this() {
    type_ = other.type_;
    currentVelocity_ = other.currentVelocity_;
    currentEncoder_ = other.currentEncoder_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MotorResponse Clone() {
    return new MotorResponse(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::MessageType type_ = global::MessageType.MsgNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MessageType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "current_velocity" field.</summary>
  public const int CurrentVelocityFieldNumber = 2;
  private int currentVelocity_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CurrentVelocity {
    get { return currentVelocity_; }
    set {
      currentVelocity_ = value;
    }
  }

  /// <summary>Field number for the "current_encoder" field.</summary>
  public const int CurrentEncoderFieldNumber = 3;
  private int currentEncoder_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CurrentEncoder {
    get { return currentEncoder_; }
    set {
      currentEncoder_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MotorResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MotorResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (CurrentVelocity != other.CurrentVelocity) return false;
    if (CurrentEncoder != other.CurrentEncoder) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::MessageType.MsgNone) hash ^= Type.GetHashCode();
    if (CurrentVelocity != 0) hash ^= CurrentVelocity.GetHashCode();
    if (CurrentEncoder != 0) hash ^= CurrentEncoder.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (CurrentVelocity != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(CurrentVelocity);
    }
    if (CurrentEncoder != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(CurrentEncoder);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::MessageType.MsgNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (CurrentVelocity != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(CurrentVelocity);
    }
    if (CurrentEncoder != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(CurrentEncoder);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::MessageType.MsgNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (CurrentVelocity != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentVelocity);
    }
    if (CurrentEncoder != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentEncoder);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MotorResponse other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::MessageType.MsgNone) {
      Type = other.Type;
    }
    if (other.CurrentVelocity != 0) {
      CurrentVelocity = other.CurrentVelocity;
    }
    if (other.CurrentEncoder != 0) {
      CurrentEncoder = other.CurrentEncoder;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          CurrentVelocity = input.ReadInt32();
          break;
        }
        case 24: {
          CurrentEncoder = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::MessageType) input.ReadEnum();
          break;
        }
        case 16: {
          CurrentVelocity = input.ReadInt32();
          break;
        }
        case 24: {
          CurrentEncoder = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
