/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_IO_PB_H_INCLUDED
#define PB_IO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MessageType {
    MessageType_MSG_NONE = 0,
    MessageType_MSG_PING_REQUEST = 1,
    MessageType_MSG_PING_RESPONSE = 2,
    MessageType_MSG_BMS_REQUEST = 3,
    MessageType_MSG_BMS_RESPONSE = 4,
    MessageType_MSG_IMU_REQUEST = 5,
    MessageType_MSG_IMU_RESPONSE = 6,
    MessageType_MSG_MOTOR_REQUEST = 7,
    MessageType_MSG_MOTOR_RESPONSE = 8
} MessageType;

/* Struct definitions */
typedef struct _EmptyResponse {
    MessageType type;
} EmptyResponse;

/* ping test */
typedef struct _PingRequest {
    MessageType type;
    int32_t data_0;
    int32_t data_1;
    int32_t data_2;
    int32_t data_3;
} PingRequest;

typedef struct _PingResponse {
    MessageType type;
    int32_t data_0;
    int32_t data_1;
    int32_t data_2;
    int32_t data_3;
} PingResponse;

/* baterry power management */
typedef struct _BMSRequest {
    MessageType type;
    bool main_bus_a_enable;
    bool main_bus_b_enable;
} BMSRequest;

typedef struct _BMSResponse {
    MessageType type;
    int32_t cell_voltage_1;
    int32_t cell_voltage_2;
    int32_t cell_voltage_3;
    int32_t main_bus_a_voltage;
    int32_t main_bus_a_current;
    int32_t main_bus_b_voltage;
    int32_t main_bus_b_current;
    bool main_bus_a_enabled;
    bool main_bus_b_enabled;
} BMSResponse;

/* IMU + GPS unit */
typedef struct _IMURequest {
    MessageType type;
} IMURequest;

typedef struct _IMUResponse {
    MessageType type;
    int32_t roll;
    int32_t pitch;
    int32_t yaw;
    int32_t gps_x;
    int32_t gps_y;
    int32_t gps_h;
} IMUResponse;

/* motor controll unit */
typedef struct _MotorRequest {
    MessageType type;
    int32_t required_velocity;
    int32_t maximum_velocity;
    int32_t maximum_acceleration;
} MotorRequest;

typedef struct _MotorResponse {
    MessageType type;
    int32_t current_velocity;
    int32_t current_encoder;
} MotorResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MessageType_MIN MessageType_MSG_NONE
#define _MessageType_MAX MessageType_MSG_MOTOR_RESPONSE
#define _MessageType_ARRAYSIZE ((MessageType)(MessageType_MSG_MOTOR_RESPONSE+1))

#define EmptyResponse_type_ENUMTYPE MessageType

#define PingRequest_type_ENUMTYPE MessageType

#define PingResponse_type_ENUMTYPE MessageType

#define BMSRequest_type_ENUMTYPE MessageType

#define BMSResponse_type_ENUMTYPE MessageType

#define IMURequest_type_ENUMTYPE MessageType

#define IMUResponse_type_ENUMTYPE MessageType

#define MotorRequest_type_ENUMTYPE MessageType

#define MotorResponse_type_ENUMTYPE MessageType


/* Initializer values for message structs */
#define EmptyResponse_init_default               {_MessageType_MIN}
#define PingRequest_init_default                 {_MessageType_MIN, 0, 0, 0, 0}
#define PingResponse_init_default                {_MessageType_MIN, 0, 0, 0, 0}
#define BMSRequest_init_default                  {_MessageType_MIN, 0, 0}
#define BMSResponse_init_default                 {_MessageType_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define IMURequest_init_default                  {_MessageType_MIN}
#define IMUResponse_init_default                 {_MessageType_MIN, 0, 0, 0, 0, 0, 0}
#define MotorRequest_init_default                {_MessageType_MIN, 0, 0, 0}
#define MotorResponse_init_default               {_MessageType_MIN, 0, 0}
#define EmptyResponse_init_zero                  {_MessageType_MIN}
#define PingRequest_init_zero                    {_MessageType_MIN, 0, 0, 0, 0}
#define PingResponse_init_zero                   {_MessageType_MIN, 0, 0, 0, 0}
#define BMSRequest_init_zero                     {_MessageType_MIN, 0, 0}
#define BMSResponse_init_zero                    {_MessageType_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define IMURequest_init_zero                     {_MessageType_MIN}
#define IMUResponse_init_zero                    {_MessageType_MIN, 0, 0, 0, 0, 0, 0}
#define MotorRequest_init_zero                   {_MessageType_MIN, 0, 0, 0}
#define MotorResponse_init_zero                  {_MessageType_MIN, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define EmptyResponse_type_tag                   1
#define PingRequest_type_tag                     1
#define PingRequest_data_0_tag                   2
#define PingRequest_data_1_tag                   3
#define PingRequest_data_2_tag                   4
#define PingRequest_data_3_tag                   5
#define PingResponse_type_tag                    1
#define PingResponse_data_0_tag                  2
#define PingResponse_data_1_tag                  3
#define PingResponse_data_2_tag                  4
#define PingResponse_data_3_tag                  5
#define BMSRequest_type_tag                      1
#define BMSRequest_main_bus_a_enable_tag         2
#define BMSRequest_main_bus_b_enable_tag         3
#define BMSResponse_type_tag                     1
#define BMSResponse_cell_voltage_1_tag           2
#define BMSResponse_cell_voltage_2_tag           3
#define BMSResponse_cell_voltage_3_tag           4
#define BMSResponse_main_bus_a_voltage_tag       5
#define BMSResponse_main_bus_a_current_tag       6
#define BMSResponse_main_bus_b_voltage_tag       7
#define BMSResponse_main_bus_b_current_tag       8
#define BMSResponse_main_bus_a_enabled_tag       9
#define BMSResponse_main_bus_b_enabled_tag       10
#define IMURequest_type_tag                      1
#define IMUResponse_type_tag                     1
#define IMUResponse_roll_tag                     2
#define IMUResponse_pitch_tag                    3
#define IMUResponse_yaw_tag                      4
#define IMUResponse_gps_x_tag                    5
#define IMUResponse_gps_y_tag                    6
#define IMUResponse_gps_h_tag                    7
#define MotorRequest_type_tag                    1
#define MotorRequest_required_velocity_tag       2
#define MotorRequest_maximum_velocity_tag        3
#define MotorRequest_maximum_acceleration_tag    4
#define MotorResponse_type_tag                   1
#define MotorResponse_current_velocity_tag       2
#define MotorResponse_current_encoder_tag        3

/* Struct field encoding specification for nanopb */
#define EmptyResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1)
#define EmptyResponse_CALLBACK NULL
#define EmptyResponse_DEFAULT NULL

#define PingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    data_0,            2) \
X(a, STATIC,   SINGULAR, INT32,    data_1,            3) \
X(a, STATIC,   SINGULAR, INT32,    data_2,            4) \
X(a, STATIC,   SINGULAR, INT32,    data_3,            5)
#define PingRequest_CALLBACK NULL
#define PingRequest_DEFAULT NULL

#define PingResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    data_0,            2) \
X(a, STATIC,   SINGULAR, INT32,    data_1,            3) \
X(a, STATIC,   SINGULAR, INT32,    data_2,            4) \
X(a, STATIC,   SINGULAR, INT32,    data_3,            5)
#define PingResponse_CALLBACK NULL
#define PingResponse_DEFAULT NULL

#define BMSRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, BOOL,     main_bus_a_enable,   2) \
X(a, STATIC,   SINGULAR, BOOL,     main_bus_b_enable,   3)
#define BMSRequest_CALLBACK NULL
#define BMSRequest_DEFAULT NULL

#define BMSResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    cell_voltage_1,    2) \
X(a, STATIC,   SINGULAR, INT32,    cell_voltage_2,    3) \
X(a, STATIC,   SINGULAR, INT32,    cell_voltage_3,    4) \
X(a, STATIC,   SINGULAR, INT32,    main_bus_a_voltage,   5) \
X(a, STATIC,   SINGULAR, INT32,    main_bus_a_current,   6) \
X(a, STATIC,   SINGULAR, INT32,    main_bus_b_voltage,   7) \
X(a, STATIC,   SINGULAR, INT32,    main_bus_b_current,   8) \
X(a, STATIC,   SINGULAR, BOOL,     main_bus_a_enabled,   9) \
X(a, STATIC,   SINGULAR, BOOL,     main_bus_b_enabled,  10)
#define BMSResponse_CALLBACK NULL
#define BMSResponse_DEFAULT NULL

#define IMURequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1)
#define IMURequest_CALLBACK NULL
#define IMURequest_DEFAULT NULL

#define IMUResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    roll,              2) \
X(a, STATIC,   SINGULAR, INT32,    pitch,             3) \
X(a, STATIC,   SINGULAR, INT32,    yaw,               4) \
X(a, STATIC,   SINGULAR, INT32,    gps_x,             5) \
X(a, STATIC,   SINGULAR, INT32,    gps_y,             6) \
X(a, STATIC,   SINGULAR, INT32,    gps_h,             7)
#define IMUResponse_CALLBACK NULL
#define IMUResponse_DEFAULT NULL

#define MotorRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    required_velocity,   2) \
X(a, STATIC,   SINGULAR, INT32,    maximum_velocity,   3) \
X(a, STATIC,   SINGULAR, INT32,    maximum_acceleration,   4)
#define MotorRequest_CALLBACK NULL
#define MotorRequest_DEFAULT NULL

#define MotorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    current_velocity,   2) \
X(a, STATIC,   SINGULAR, INT32,    current_encoder,   3)
#define MotorResponse_CALLBACK NULL
#define MotorResponse_DEFAULT NULL

extern const pb_msgdesc_t EmptyResponse_msg;
extern const pb_msgdesc_t PingRequest_msg;
extern const pb_msgdesc_t PingResponse_msg;
extern const pb_msgdesc_t BMSRequest_msg;
extern const pb_msgdesc_t BMSResponse_msg;
extern const pb_msgdesc_t IMURequest_msg;
extern const pb_msgdesc_t IMUResponse_msg;
extern const pb_msgdesc_t MotorRequest_msg;
extern const pb_msgdesc_t MotorResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define EmptyResponse_fields &EmptyResponse_msg
#define PingRequest_fields &PingRequest_msg
#define PingResponse_fields &PingResponse_msg
#define BMSRequest_fields &BMSRequest_msg
#define BMSResponse_fields &BMSResponse_msg
#define IMURequest_fields &IMURequest_msg
#define IMUResponse_fields &IMUResponse_msg
#define MotorRequest_fields &MotorRequest_msg
#define MotorResponse_fields &MotorResponse_msg

/* Maximum encoded size of messages (where known) */
#define BMSRequest_size                          6
#define BMSResponse_size                         83
#define EmptyResponse_size                       2
#define IMURequest_size                          2
#define IMUResponse_size                         68
#define IO_PB_H_MAX_SIZE                         BMSResponse_size
#define MotorRequest_size                        35
#define MotorResponse_size                       24
#define PingRequest_size                         46
#define PingResponse_size                        46

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
