/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "io.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(EmptyResponse, EmptyResponse, AUTO)


PB_BIND(PingRequest, PingRequest, AUTO)


PB_BIND(PingResponse, PingResponse, AUTO)


PB_BIND(BMSRequest, BMSRequest, AUTO)


PB_BIND(BMSResponse, BMSResponse, AUTO)


PB_BIND(IMURequest, IMURequest, AUTO)


PB_BIND(IMUResponse, IMUResponse, AUTO)


PB_BIND(MotorRequest, MotorRequest, AUTO)


PB_BIND(MotorResponse, MotorResponse, AUTO)





