/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "ll.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(robot_hw_endpoint_grpc_LLEmptyResponse, robot_hw_endpoint_grpc_LLEmptyResponse, AUTO)


PB_BIND(robot_hw_endpoint_grpc_LLStatusRequest, robot_hw_endpoint_grpc_LLStatusRequest, AUTO)


PB_BIND(robot_hw_endpoint_grpc_LLPingRequest, robot_hw_endpoint_grpc_LLPingRequest, AUTO)


PB_BIND(robot_hw_endpoint_grpc_LLPingResponse, robot_hw_endpoint_grpc_LLPingResponse, AUTO)


PB_BIND(robot_hw_endpoint_grpc_LLBMSRequest, robot_hw_endpoint_grpc_LLBMSRequest, AUTO)


PB_BIND(robot_hw_endpoint_grpc_LLBMSResponse, robot_hw_endpoint_grpc_LLBMSResponse, AUTO)


PB_BIND(robot_hw_endpoint_grpc_LLIMURequest, robot_hw_endpoint_grpc_LLIMURequest, AUTO)


PB_BIND(robot_hw_endpoint_grpc_LLIMUResponse, robot_hw_endpoint_grpc_LLIMUResponse, AUTO)


PB_BIND(robot_hw_endpoint_grpc_LLMotorRequest, robot_hw_endpoint_grpc_LLMotorRequest, AUTO)


PB_BIND(robot_hw_endpoint_grpc_LLMotorResponse, robot_hw_endpoint_grpc_LLMotorResponse, AUTO)





