/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ROBOT_HW_ENDPOINT_GRPC_LL_PB_H_INCLUDED
#define PB_ROBOT_HW_ENDPOINT_GRPC_LL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _robot_hw_endpoint_grpc_LLMessageType {
    robot_hw_endpoint_grpc_LLMessageType_MSG_NONE = 0,
    robot_hw_endpoint_grpc_LLMessageType_MSG_STATUS_REQUEST = 1,
    robot_hw_endpoint_grpc_LLMessageType_MSG_PING_REQUEST = 2,
    robot_hw_endpoint_grpc_LLMessageType_MSG_PING_RESPONSE = 3,
    robot_hw_endpoint_grpc_LLMessageType_MSG_BMS_REQUEST = 4,
    robot_hw_endpoint_grpc_LLMessageType_MSG_BMS_RESPONSE = 5,
    robot_hw_endpoint_grpc_LLMessageType_MSG_IMU_REQUEST = 6,
    robot_hw_endpoint_grpc_LLMessageType_MSG_IMU_RESPONSE = 7,
    robot_hw_endpoint_grpc_LLMessageType_MSG_MOTOR_REQUEST = 8,
    robot_hw_endpoint_grpc_LLMessageType_MSG_MOTOR_RESPONSE = 9
} robot_hw_endpoint_grpc_LLMessageType;

/* Struct definitions */
typedef struct _robot_hw_endpoint_grpc_LLEmptyResponse {
    robot_hw_endpoint_grpc_LLMessageType type;
} robot_hw_endpoint_grpc_LLEmptyResponse;

/* returns status, not changing any variables */
typedef struct _robot_hw_endpoint_grpc_LLStatusRequest {
    robot_hw_endpoint_grpc_LLMessageType type;
} robot_hw_endpoint_grpc_LLStatusRequest;

/* ping, mostly for connectLLn debug */
typedef struct _robot_hw_endpoint_grpc_LLPingRequest {
    robot_hw_endpoint_grpc_LLMessageType type;
    int32_t data_0;
    int32_t data_1;
    int32_t data_2;
    int32_t data_3;
} robot_hw_endpoint_grpc_LLPingRequest;

typedef struct _robot_hw_endpoint_grpc_LLPingResponse {
    robot_hw_endpoint_grpc_LLMessageType type;
    int32_t data_0;
    int32_t data_1;
    int32_t data_2;
    int32_t data_3;
} robot_hw_endpoint_grpc_LLPingResponse;

/* baterry power management */
typedef struct _robot_hw_endpoint_grpc_LLBMSRequest {
    robot_hw_endpoint_grpc_LLMessageType type;
    bool main_bus_a_enable;
    bool main_bus_b_enable;
} robot_hw_endpoint_grpc_LLBMSRequest;

typedef struct _robot_hw_endpoint_grpc_LLBMSResponse {
    robot_hw_endpoint_grpc_LLMessageType type;
    int32_t cell_voltage_1;
    int32_t cell_voltage_2;
    int32_t cell_voltage_3;
    int32_t main_bus_a_voltage;
    int32_t main_bus_a_current;
    int32_t main_bus_b_voltage;
    int32_t main_bus_b_current;
    bool main_bus_a_enabled;
    bool main_bus_b_enabled;
} robot_hw_endpoint_grpc_LLBMSResponse;

/* IMU + GPS unit */
typedef struct _robot_hw_endpoint_grpc_LLIMURequest {
    robot_hw_endpoint_grpc_LLMessageType type;
} robot_hw_endpoint_grpc_LLIMURequest;

typedef struct _robot_hw_endpoint_grpc_LLIMUResponse {
    robot_hw_endpoint_grpc_LLMessageType type;
    int32_t roll;
    int32_t pitch;
    int32_t yaw;
    int32_t gps_x;
    int32_t gps_y;
    int32_t gps_h;
} robot_hw_endpoint_grpc_LLIMUResponse;

/* motor controll unit */
typedef struct _robot_hw_endpoint_grpc_LLMotorRequest {
    robot_hw_endpoint_grpc_LLMessageType type;
    int32_t required_velocity;
    int32_t maximum_velocity;
    int32_t maximum_acceleration;
} robot_hw_endpoint_grpc_LLMotorRequest;

typedef struct _robot_hw_endpoint_grpc_LLMotorResponse {
    robot_hw_endpoint_grpc_LLMessageType type;
    int32_t current_velocity;
    int32_t current_encoder;
} robot_hw_endpoint_grpc_LLMotorResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _robot_hw_endpoint_grpc_LLMessageType_MIN robot_hw_endpoint_grpc_LLMessageType_MSG_NONE
#define _robot_hw_endpoint_grpc_LLMessageType_MAX robot_hw_endpoint_grpc_LLMessageType_MSG_MOTOR_RESPONSE
#define _robot_hw_endpoint_grpc_LLMessageType_ARRAYSIZE ((robot_hw_endpoint_grpc_LLMessageType)(robot_hw_endpoint_grpc_LLMessageType_MSG_MOTOR_RESPONSE+1))

#define robot_hw_endpoint_grpc_LLEmptyResponse_type_ENUMTYPE robot_hw_endpoint_grpc_LLMessageType

#define robot_hw_endpoint_grpc_LLStatusRequest_type_ENUMTYPE robot_hw_endpoint_grpc_LLMessageType

#define robot_hw_endpoint_grpc_LLPingRequest_type_ENUMTYPE robot_hw_endpoint_grpc_LLMessageType

#define robot_hw_endpoint_grpc_LLPingResponse_type_ENUMTYPE robot_hw_endpoint_grpc_LLMessageType

#define robot_hw_endpoint_grpc_LLBMSRequest_type_ENUMTYPE robot_hw_endpoint_grpc_LLMessageType

#define robot_hw_endpoint_grpc_LLBMSResponse_type_ENUMTYPE robot_hw_endpoint_grpc_LLMessageType

#define robot_hw_endpoint_grpc_LLIMURequest_type_ENUMTYPE robot_hw_endpoint_grpc_LLMessageType

#define robot_hw_endpoint_grpc_LLIMUResponse_type_ENUMTYPE robot_hw_endpoint_grpc_LLMessageType

#define robot_hw_endpoint_grpc_LLMotorRequest_type_ENUMTYPE robot_hw_endpoint_grpc_LLMessageType

#define robot_hw_endpoint_grpc_LLMotorResponse_type_ENUMTYPE robot_hw_endpoint_grpc_LLMessageType


/* Initializer values for message structs */
#define robot_hw_endpoint_grpc_LLEmptyResponse_init_default {_robot_hw_endpoint_grpc_LLMessageType_MIN}
#define robot_hw_endpoint_grpc_LLStatusRequest_init_default {_robot_hw_endpoint_grpc_LLMessageType_MIN}
#define robot_hw_endpoint_grpc_LLPingRequest_init_default {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0, 0, 0}
#define robot_hw_endpoint_grpc_LLPingResponse_init_default {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0, 0, 0}
#define robot_hw_endpoint_grpc_LLBMSRequest_init_default {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0}
#define robot_hw_endpoint_grpc_LLBMSResponse_init_default {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define robot_hw_endpoint_grpc_LLIMURequest_init_default {_robot_hw_endpoint_grpc_LLMessageType_MIN}
#define robot_hw_endpoint_grpc_LLIMUResponse_init_default {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0, 0, 0, 0, 0}
#define robot_hw_endpoint_grpc_LLMotorRequest_init_default {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0, 0}
#define robot_hw_endpoint_grpc_LLMotorResponse_init_default {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0}
#define robot_hw_endpoint_grpc_LLEmptyResponse_init_zero {_robot_hw_endpoint_grpc_LLMessageType_MIN}
#define robot_hw_endpoint_grpc_LLStatusRequest_init_zero {_robot_hw_endpoint_grpc_LLMessageType_MIN}
#define robot_hw_endpoint_grpc_LLPingRequest_init_zero {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0, 0, 0}
#define robot_hw_endpoint_grpc_LLPingResponse_init_zero {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0, 0, 0}
#define robot_hw_endpoint_grpc_LLBMSRequest_init_zero {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0}
#define robot_hw_endpoint_grpc_LLBMSResponse_init_zero {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define robot_hw_endpoint_grpc_LLIMURequest_init_zero {_robot_hw_endpoint_grpc_LLMessageType_MIN}
#define robot_hw_endpoint_grpc_LLIMUResponse_init_zero {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0, 0, 0, 0, 0}
#define robot_hw_endpoint_grpc_LLMotorRequest_init_zero {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0, 0}
#define robot_hw_endpoint_grpc_LLMotorResponse_init_zero {_robot_hw_endpoint_grpc_LLMessageType_MIN, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define robot_hw_endpoint_grpc_LLEmptyResponse_type_tag 1
#define robot_hw_endpoint_grpc_LLStatusRequest_type_tag 1
#define robot_hw_endpoint_grpc_LLPingRequest_type_tag 1
#define robot_hw_endpoint_grpc_LLPingRequest_data_0_tag 2
#define robot_hw_endpoint_grpc_LLPingRequest_data_1_tag 3
#define robot_hw_endpoint_grpc_LLPingRequest_data_2_tag 4
#define robot_hw_endpoint_grpc_LLPingRequest_data_3_tag 5
#define robot_hw_endpoint_grpc_LLPingResponse_type_tag 1
#define robot_hw_endpoint_grpc_LLPingResponse_data_0_tag 2
#define robot_hw_endpoint_grpc_LLPingResponse_data_1_tag 3
#define robot_hw_endpoint_grpc_LLPingResponse_data_2_tag 4
#define robot_hw_endpoint_grpc_LLPingResponse_data_3_tag 5
#define robot_hw_endpoint_grpc_LLBMSRequest_type_tag 1
#define robot_hw_endpoint_grpc_LLBMSRequest_main_bus_a_enable_tag 2
#define robot_hw_endpoint_grpc_LLBMSRequest_main_bus_b_enable_tag 3
#define robot_hw_endpoint_grpc_LLBMSResponse_type_tag 1
#define robot_hw_endpoint_grpc_LLBMSResponse_cell_voltage_1_tag 2
#define robot_hw_endpoint_grpc_LLBMSResponse_cell_voltage_2_tag 3
#define robot_hw_endpoint_grpc_LLBMSResponse_cell_voltage_3_tag 4
#define robot_hw_endpoint_grpc_LLBMSResponse_main_bus_a_voltage_tag 5
#define robot_hw_endpoint_grpc_LLBMSResponse_main_bus_a_current_tag 6
#define robot_hw_endpoint_grpc_LLBMSResponse_main_bus_b_voltage_tag 7
#define robot_hw_endpoint_grpc_LLBMSResponse_main_bus_b_current_tag 8
#define robot_hw_endpoint_grpc_LLBMSResponse_main_bus_a_enabled_tag 9
#define robot_hw_endpoint_grpc_LLBMSResponse_main_bus_b_enabled_tag 10
#define robot_hw_endpoint_grpc_LLIMURequest_type_tag 1
#define robot_hw_endpoint_grpc_LLIMUResponse_type_tag 1
#define robot_hw_endpoint_grpc_LLIMUResponse_roll_tag 2
#define robot_hw_endpoint_grpc_LLIMUResponse_pitch_tag 3
#define robot_hw_endpoint_grpc_LLIMUResponse_yaw_tag 4
#define robot_hw_endpoint_grpc_LLIMUResponse_gps_x_tag 5
#define robot_hw_endpoint_grpc_LLIMUResponse_gps_y_tag 6
#define robot_hw_endpoint_grpc_LLIMUResponse_gps_h_tag 7
#define robot_hw_endpoint_grpc_LLMotorRequest_type_tag 1
#define robot_hw_endpoint_grpc_LLMotorRequest_required_velocity_tag 2
#define robot_hw_endpoint_grpc_LLMotorRequest_maximum_velocity_tag 3
#define robot_hw_endpoint_grpc_LLMotorRequest_maximum_acceleration_tag 4
#define robot_hw_endpoint_grpc_LLMotorResponse_type_tag 1
#define robot_hw_endpoint_grpc_LLMotorResponse_current_velocity_tag 2
#define robot_hw_endpoint_grpc_LLMotorResponse_current_encoder_tag 3

/* Struct field encoding specification for nanopb */
#define robot_hw_endpoint_grpc_LLEmptyResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1)
#define robot_hw_endpoint_grpc_LLEmptyResponse_CALLBACK NULL
#define robot_hw_endpoint_grpc_LLEmptyResponse_DEFAULT NULL

#define robot_hw_endpoint_grpc_LLStatusRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1)
#define robot_hw_endpoint_grpc_LLStatusRequest_CALLBACK NULL
#define robot_hw_endpoint_grpc_LLStatusRequest_DEFAULT NULL

#define robot_hw_endpoint_grpc_LLPingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    data_0,            2) \
X(a, STATIC,   SINGULAR, INT32,    data_1,            3) \
X(a, STATIC,   SINGULAR, INT32,    data_2,            4) \
X(a, STATIC,   SINGULAR, INT32,    data_3,            5)
#define robot_hw_endpoint_grpc_LLPingRequest_CALLBACK NULL
#define robot_hw_endpoint_grpc_LLPingRequest_DEFAULT NULL

#define robot_hw_endpoint_grpc_LLPingResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    data_0,            2) \
X(a, STATIC,   SINGULAR, INT32,    data_1,            3) \
X(a, STATIC,   SINGULAR, INT32,    data_2,            4) \
X(a, STATIC,   SINGULAR, INT32,    data_3,            5)
#define robot_hw_endpoint_grpc_LLPingResponse_CALLBACK NULL
#define robot_hw_endpoint_grpc_LLPingResponse_DEFAULT NULL

#define robot_hw_endpoint_grpc_LLBMSRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, BOOL,     main_bus_a_enable,   2) \
X(a, STATIC,   SINGULAR, BOOL,     main_bus_b_enable,   3)
#define robot_hw_endpoint_grpc_LLBMSRequest_CALLBACK NULL
#define robot_hw_endpoint_grpc_LLBMSRequest_DEFAULT NULL

#define robot_hw_endpoint_grpc_LLBMSResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    cell_voltage_1,    2) \
X(a, STATIC,   SINGULAR, INT32,    cell_voltage_2,    3) \
X(a, STATIC,   SINGULAR, INT32,    cell_voltage_3,    4) \
X(a, STATIC,   SINGULAR, INT32,    main_bus_a_voltage,   5) \
X(a, STATIC,   SINGULAR, INT32,    main_bus_a_current,   6) \
X(a, STATIC,   SINGULAR, INT32,    main_bus_b_voltage,   7) \
X(a, STATIC,   SINGULAR, INT32,    main_bus_b_current,   8) \
X(a, STATIC,   SINGULAR, BOOL,     main_bus_a_enabled,   9) \
X(a, STATIC,   SINGULAR, BOOL,     main_bus_b_enabled,  10)
#define robot_hw_endpoint_grpc_LLBMSResponse_CALLBACK NULL
#define robot_hw_endpoint_grpc_LLBMSResponse_DEFAULT NULL

#define robot_hw_endpoint_grpc_LLIMURequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1)
#define robot_hw_endpoint_grpc_LLIMURequest_CALLBACK NULL
#define robot_hw_endpoint_grpc_LLIMURequest_DEFAULT NULL

#define robot_hw_endpoint_grpc_LLIMUResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    roll,              2) \
X(a, STATIC,   SINGULAR, INT32,    pitch,             3) \
X(a, STATIC,   SINGULAR, INT32,    yaw,               4) \
X(a, STATIC,   SINGULAR, INT32,    gps_x,             5) \
X(a, STATIC,   SINGULAR, INT32,    gps_y,             6) \
X(a, STATIC,   SINGULAR, INT32,    gps_h,             7)
#define robot_hw_endpoint_grpc_LLIMUResponse_CALLBACK NULL
#define robot_hw_endpoint_grpc_LLIMUResponse_DEFAULT NULL

#define robot_hw_endpoint_grpc_LLMotorRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    required_velocity,   2) \
X(a, STATIC,   SINGULAR, INT32,    maximum_velocity,   3) \
X(a, STATIC,   SINGULAR, INT32,    maximum_acceleration,   4)
#define robot_hw_endpoint_grpc_LLMotorRequest_CALLBACK NULL
#define robot_hw_endpoint_grpc_LLMotorRequest_DEFAULT NULL

#define robot_hw_endpoint_grpc_LLMotorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    current_velocity,   2) \
X(a, STATIC,   SINGULAR, INT32,    current_encoder,   3)
#define robot_hw_endpoint_grpc_LLMotorResponse_CALLBACK NULL
#define robot_hw_endpoint_grpc_LLMotorResponse_DEFAULT NULL

extern const pb_msgdesc_t robot_hw_endpoint_grpc_LLEmptyResponse_msg;
extern const pb_msgdesc_t robot_hw_endpoint_grpc_LLStatusRequest_msg;
extern const pb_msgdesc_t robot_hw_endpoint_grpc_LLPingRequest_msg;
extern const pb_msgdesc_t robot_hw_endpoint_grpc_LLPingResponse_msg;
extern const pb_msgdesc_t robot_hw_endpoint_grpc_LLBMSRequest_msg;
extern const pb_msgdesc_t robot_hw_endpoint_grpc_LLBMSResponse_msg;
extern const pb_msgdesc_t robot_hw_endpoint_grpc_LLIMURequest_msg;
extern const pb_msgdesc_t robot_hw_endpoint_grpc_LLIMUResponse_msg;
extern const pb_msgdesc_t robot_hw_endpoint_grpc_LLMotorRequest_msg;
extern const pb_msgdesc_t robot_hw_endpoint_grpc_LLMotorResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define robot_hw_endpoint_grpc_LLEmptyResponse_fields &robot_hw_endpoint_grpc_LLEmptyResponse_msg
#define robot_hw_endpoint_grpc_LLStatusRequest_fields &robot_hw_endpoint_grpc_LLStatusRequest_msg
#define robot_hw_endpoint_grpc_LLPingRequest_fields &robot_hw_endpoint_grpc_LLPingRequest_msg
#define robot_hw_endpoint_grpc_LLPingResponse_fields &robot_hw_endpoint_grpc_LLPingResponse_msg
#define robot_hw_endpoint_grpc_LLBMSRequest_fields &robot_hw_endpoint_grpc_LLBMSRequest_msg
#define robot_hw_endpoint_grpc_LLBMSResponse_fields &robot_hw_endpoint_grpc_LLBMSResponse_msg
#define robot_hw_endpoint_grpc_LLIMURequest_fields &robot_hw_endpoint_grpc_LLIMURequest_msg
#define robot_hw_endpoint_grpc_LLIMUResponse_fields &robot_hw_endpoint_grpc_LLIMUResponse_msg
#define robot_hw_endpoint_grpc_LLMotorRequest_fields &robot_hw_endpoint_grpc_LLMotorRequest_msg
#define robot_hw_endpoint_grpc_LLMotorResponse_fields &robot_hw_endpoint_grpc_LLMotorResponse_msg

/* Maximum encoded size of messages (where known) */
#define ROBOT_HW_ENDPOINT_GRPC_LL_PB_H_MAX_SIZE  robot_hw_endpoint_grpc_LLBMSResponse_size
#define robot_hw_endpoint_grpc_LLBMSRequest_size 6
#define robot_hw_endpoint_grpc_LLBMSResponse_size 83
#define robot_hw_endpoint_grpc_LLEmptyResponse_size 2
#define robot_hw_endpoint_grpc_LLIMURequest_size 2
#define robot_hw_endpoint_grpc_LLIMUResponse_size 68
#define robot_hw_endpoint_grpc_LLMotorRequest_size 35
#define robot_hw_endpoint_grpc_LLMotorResponse_size 24
#define robot_hw_endpoint_grpc_LLPingRequest_size 46
#define robot_hw_endpoint_grpc_LLPingResponse_size 46
#define robot_hw_endpoint_grpc_LLStatusRequest_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
