/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LL_PB_H_INCLUDED
#define PB_LL_PB_H_INCLUDED

/* Enum definitions */
typedef enum _LLMessageType {
    LLMessageType_MSG_NONE = 0,
    LLMessageType_MSG_STATUS_REQUEST = 1,
    LLMessageType_MSG_PING_REQUEST = 2,
    LLMessageType_MSG_PING_RESPONSE = 3,
    LLMessageType_MSG_BMS_REQUEST = 4,
    LLMessageType_MSG_BMS_RESPONSE = 5,
    LLMessageType_MSG_IMU_REQUEST = 6,
    LLMessageType_MSG_IMU_RESPONSE = 7,
    LLMessageType_MSG_MOTOR_REQUEST = 8,
    LLMessageType_MSG_MOTOR_RESPONSE = 9
} LLMessageType;

/* Struct definitions */
typedef struct _LLEmptyResponse {
    uint32_t type;
} LLEmptyResponse;

/* returns status, not changing any variables */
typedef struct _LLStatusRequest {
    uint32_t type;
} LLStatusRequest;

/* ping, mostly for connectLLn debug */
typedef struct _LLPingRequest {
    uint32_t type;
    int32_t data_0;
    int32_t data_1;
    int32_t data_2;
    int32_t data_3;
} LLPingRequest;

typedef struct _LLPingResponse {
    uint32_t type;
    int32_t data_0;
    int32_t data_1;
    int32_t data_2;
    int32_t data_3;
} LLPingResponse;

/* baterry power management */
typedef struct _LLBMSRequest {
    uint32_t type;
    bool main_bus_a_enable;
    bool main_bus_b_enable;
} LLBMSRequest;

typedef struct _LLBMSResponse {
    uint32_t type;
    int32_t cell_voltage_1;
    int32_t cell_voltage_2;
    int32_t cell_voltage_3;
    int32_t main_bus_a_voltage;
    int32_t main_bus_a_current;
    int32_t main_bus_b_voltage;
    int32_t main_bus_b_current;
    bool main_bus_a_enabled;
    bool main_bus_b_enabled;
} LLBMSResponse;

/* IMU + GPS unit */
typedef struct _LLIMURequest {
    uint32_t type;
} LLIMURequest;

typedef struct _LLIMUResponse {
    uint32_t type;
    int32_t roll;
    int32_t pitch;
    int32_t yaw;
    int32_t gps_x;
    int32_t gps_y;
    int32_t gps_h;
} LLIMUResponse;

/* motor controll unit */
typedef struct _LLMotorRequest {
    uint32_t type;
    int32_t required_velocity;
    int32_t maximum_velocity;
    int32_t maximum_acceleration;
} LLMotorRequest;

typedef struct _LLMotorResponse {
    uint32_t type;
    int32_t current_velocity;
    int32_t current_encoder;
} LLMotorResponse;



#endif
